'use strict'

import * as $ from "jquery"
import 'moment'
import 'lodash'
import './main.styl'
import './percentages/multi-doughnut-chart.js'
import  './vendor/jquery.circlicful.js'
import './percentages/doughnut-chart.js'
import './standard_buttons/standard_buttons_ripple.js'
import  './sliders/sliders.js'
import  './vendor/jquery.progressbar.js'
import './stages/stages.js'
import './location/gmaps.js'
import './vendor/clndr.js'
import './calendar/calendar.js'
